

version: '3'
services:

 server: 
  build: .
  depends_on:
   - mysql1
  container_name: server
  ports:
   - "80:8080"

 mysql1:
  image: mysql:5.7.31
  container_name: database
  ports:
   - "3306:3306"
  environment:
   MYSQL_ROOT_PASSWORD: admin
   MYSQL_DATABASE: doughnuts_database
   